on: [push]

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          compose-file: './docker/docker-compose.yml'
          down-flags: '--volumes'
